//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/git/external/keycloak-openapi/Dahag.Keycloak.OpenApiGenerator\JavaParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJavaParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class JavaParserBaseListener : IJavaParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] JavaParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] JavaParser.CompilationUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.packageDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackageDeclaration([NotNull] JavaParser.PackageDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.packageDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackageDeclaration([NotNull] JavaParser.PackageDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportDeclaration([NotNull] JavaParser.ImportDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.importDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportDeclaration([NotNull] JavaParser.ImportDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] JavaParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] JavaParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] JavaParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] JavaParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classOrInterfaceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrInterfaceModifier([NotNull] JavaParser.ClassOrInterfaceModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classOrInterfaceModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrInterfaceModifier([NotNull] JavaParser.ClassOrInterfaceModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableModifier([NotNull] JavaParser.VariableModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableModifier([NotNull] JavaParser.VariableModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] JavaParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] JavaParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameters([NotNull] JavaParser.TypeParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameters([NotNull] JavaParser.TypeParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeParameter([NotNull] JavaParser.TypeParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeParameter([NotNull] JavaParser.TypeParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeBound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeBound([NotNull] JavaParser.TypeBoundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeBound"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeBound([NotNull] JavaParser.TypeBoundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclaration([NotNull] JavaParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclaration([NotNull] JavaParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumConstants"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumConstants([NotNull] JavaParser.EnumConstantsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumConstants"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumConstants([NotNull] JavaParser.EnumConstantsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumConstant([NotNull] JavaParser.EnumConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumConstant([NotNull] JavaParser.EnumConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumBodyDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBodyDeclarations([NotNull] JavaParser.EnumBodyDeclarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumBodyDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBodyDeclarations([NotNull] JavaParser.EnumBodyDeclarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDeclaration([NotNull] JavaParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDeclaration([NotNull] JavaParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] JavaParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] JavaParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceBody([NotNull] JavaParser.InterfaceBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceBody([NotNull] JavaParser.InterfaceBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBodyDeclaration([NotNull] JavaParser.ClassBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBodyDeclaration([NotNull] JavaParser.ClassBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDeclaration([NotNull] JavaParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDeclaration([NotNull] JavaParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] JavaParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] JavaParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodBody([NotNull] JavaParser.MethodBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.methodBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodBody([NotNull] JavaParser.MethodBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeTypeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeTypeOrVoid([NotNull] JavaParser.TypeTypeOrVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeTypeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeTypeOrVoid([NotNull] JavaParser.TypeTypeOrVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.genericMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericMethodDeclaration([NotNull] JavaParser.GenericMethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.genericMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericMethodDeclaration([NotNull] JavaParser.GenericMethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.genericConstructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericConstructorDeclaration([NotNull] JavaParser.GenericConstructorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.genericConstructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericConstructorDeclaration([NotNull] JavaParser.GenericConstructorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstructorDeclaration([NotNull] JavaParser.ConstructorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.constructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstructorDeclaration([NotNull] JavaParser.ConstructorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDeclaration([NotNull] JavaParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.fieldDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDeclaration([NotNull] JavaParser.FieldDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceBodyDeclaration([NotNull] JavaParser.InterfaceBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceBodyDeclaration([NotNull] JavaParser.InterfaceBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceMemberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMemberDeclaration([NotNull] JavaParser.InterfaceMemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceMemberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMemberDeclaration([NotNull] JavaParser.InterfaceMemberDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.constDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstDeclaration([NotNull] JavaParser.ConstDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.constDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstDeclaration([NotNull] JavaParser.ConstDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.constantDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantDeclarator([NotNull] JavaParser.ConstantDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.constantDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantDeclarator([NotNull] JavaParser.ConstantDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMethodDeclaration([NotNull] JavaParser.InterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMethodDeclaration([NotNull] JavaParser.InterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceMethodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceMethodModifier([NotNull] JavaParser.InterfaceMethodModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceMethodModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceMethodModifier([NotNull] JavaParser.InterfaceMethodModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.genericInterfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericInterfaceMethodDeclaration([NotNull] JavaParser.GenericInterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.genericInterfaceMethodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericInterfaceMethodDeclaration([NotNull] JavaParser.GenericInterfaceMethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceCommonBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceCommonBodyDeclaration([NotNull] JavaParser.InterfaceCommonBodyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceCommonBodyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceCommonBodyDeclaration([NotNull] JavaParser.InterfaceCommonBodyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarators([NotNull] JavaParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableDeclarators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarators([NotNull] JavaParser.VariableDeclaratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] JavaParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] JavaParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaratorId([NotNull] JavaParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableDeclaratorId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaratorId([NotNull] JavaParser.VariableDeclaratorIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableInitializer([NotNull] JavaParser.VariableInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableInitializer([NotNull] JavaParser.VariableInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayInitializer([NotNull] JavaParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.arrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayInitializer([NotNull] JavaParser.ArrayInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classOrInterfaceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassOrInterfaceType([NotNull] JavaParser.ClassOrInterfaceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classOrInterfaceType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassOrInterfaceType([NotNull] JavaParser.ClassOrInterfaceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgument([NotNull] JavaParser.TypeArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeArgument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgument([NotNull] JavaParser.TypeArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedNameList([NotNull] JavaParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedNameList([NotNull] JavaParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameters([NotNull] JavaParser.FormalParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.formalParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameters([NotNull] JavaParser.FormalParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.receiverParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReceiverParameter([NotNull] JavaParser.ReceiverParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.receiverParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReceiverParameter([NotNull] JavaParser.ReceiverParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterList([NotNull] JavaParser.FormalParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterList([NotNull] JavaParser.FormalParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameter([NotNull] JavaParser.FormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.formalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameter([NotNull] JavaParser.FormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLastFormalParameter([NotNull] JavaParser.LastFormalParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lastFormalParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLastFormalParameter([NotNull] JavaParser.LastFormalParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaLVTIList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaLVTIList([NotNull] JavaParser.LambdaLVTIListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaLVTIList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaLVTIList([NotNull] JavaParser.LambdaLVTIListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaLVTIParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaLVTIParameter([NotNull] JavaParser.LambdaLVTIParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaLVTIParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaLVTIParameter([NotNull] JavaParser.LambdaLVTIParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] JavaParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] JavaParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] JavaParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] JavaParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] JavaParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] JavaParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteral([NotNull] JavaParser.FloatLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteral([NotNull] JavaParser.FloatLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.altAnnotationQualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAltAnnotationQualifiedName([NotNull] JavaParser.AltAnnotationQualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.altAnnotationQualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAltAnnotationQualifiedName([NotNull] JavaParser.AltAnnotationQualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] JavaParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] JavaParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValuePairs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValuePairs([NotNull] JavaParser.ElementValuePairsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValuePairs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValuePairs([NotNull] JavaParser.ElementValuePairsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValuePair([NotNull] JavaParser.ElementValuePairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValuePair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValuePair([NotNull] JavaParser.ElementValuePairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValue([NotNull] JavaParser.ElementValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValue([NotNull] JavaParser.ElementValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValueArrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementValueArrayInitializer([NotNull] JavaParser.ElementValueArrayInitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValueArrayInitializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementValueArrayInitializer([NotNull] JavaParser.ElementValueArrayInitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeDeclaration([NotNull] JavaParser.AnnotationTypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeDeclaration([NotNull] JavaParser.AnnotationTypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeBody([NotNull] JavaParser.AnnotationTypeBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeBody([NotNull] JavaParser.AnnotationTypeBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeElementDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeElementDeclaration([NotNull] JavaParser.AnnotationTypeElementDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeElementDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeElementDeclaration([NotNull] JavaParser.AnnotationTypeElementDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeElementRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationTypeElementRest([NotNull] JavaParser.AnnotationTypeElementRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeElementRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationTypeElementRest([NotNull] JavaParser.AnnotationTypeElementRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationMethodOrConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationMethodOrConstantRest([NotNull] JavaParser.AnnotationMethodOrConstantRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationMethodOrConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationMethodOrConstantRest([NotNull] JavaParser.AnnotationMethodOrConstantRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationMethodRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationMethodRest([NotNull] JavaParser.AnnotationMethodRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationMethodRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationMethodRest([NotNull] JavaParser.AnnotationMethodRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotationConstantRest([NotNull] JavaParser.AnnotationConstantRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationConstantRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotationConstantRest([NotNull] JavaParser.AnnotationConstantRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultValue([NotNull] JavaParser.DefaultValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultValue([NotNull] JavaParser.DefaultValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.moduleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleDeclaration([NotNull] JavaParser.ModuleDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.moduleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleDeclaration([NotNull] JavaParser.ModuleDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.moduleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleBody([NotNull] JavaParser.ModuleBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.moduleBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleBody([NotNull] JavaParser.ModuleBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.moduleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleDirective([NotNull] JavaParser.ModuleDirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.moduleDirective"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleDirective([NotNull] JavaParser.ModuleDirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.requiresModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRequiresModifier([NotNull] JavaParser.RequiresModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.requiresModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRequiresModifier([NotNull] JavaParser.RequiresModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordDeclaration([NotNull] JavaParser.RecordDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordDeclaration([NotNull] JavaParser.RecordDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordHeader([NotNull] JavaParser.RecordHeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordHeader([NotNull] JavaParser.RecordHeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordComponentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordComponentList([NotNull] JavaParser.RecordComponentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordComponentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordComponentList([NotNull] JavaParser.RecordComponentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordComponent([NotNull] JavaParser.RecordComponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordComponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordComponent([NotNull] JavaParser.RecordComponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordBody([NotNull] JavaParser.RecordBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordBody([NotNull] JavaParser.RecordBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] JavaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] JavaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatement([NotNull] JavaParser.BlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatement([NotNull] JavaParser.BlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalVariableDeclaration([NotNull] JavaParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.localVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalVariableDeclaration([NotNull] JavaParser.LocalVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] JavaParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] JavaParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.localTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocalTypeDeclaration([NotNull] JavaParser.LocalTypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.localTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocalTypeDeclaration([NotNull] JavaParser.LocalTypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] JavaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] JavaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.catchClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatchClause([NotNull] JavaParser.CatchClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.catchClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatchClause([NotNull] JavaParser.CatchClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.catchType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatchType([NotNull] JavaParser.CatchTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.catchType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatchType([NotNull] JavaParser.CatchTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.finallyBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinallyBlock([NotNull] JavaParser.FinallyBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.finallyBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinallyBlock([NotNull] JavaParser.FinallyBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.resourceSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResourceSpecification([NotNull] JavaParser.ResourceSpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.resourceSpecification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResourceSpecification([NotNull] JavaParser.ResourceSpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.resources"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResources([NotNull] JavaParser.ResourcesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.resources"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResources([NotNull] JavaParser.ResourcesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResource([NotNull] JavaParser.ResourceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.resource"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResource([NotNull] JavaParser.ResourceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBlockStatementGroup([NotNull] JavaParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchBlockStatementGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBlockStatementGroup([NotNull] JavaParser.SwitchBlockStatementGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchLabel([NotNull] JavaParser.SwitchLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchLabel([NotNull] JavaParser.SwitchLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForControl([NotNull] JavaParser.ForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForControl([NotNull] JavaParser.ForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForInit([NotNull] JavaParser.ForInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.forInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForInit([NotNull] JavaParser.ForInitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enhancedForControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnhancedForControl([NotNull] JavaParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enhancedForControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnhancedForControl([NotNull] JavaParser.EnhancedForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParExpression([NotNull] JavaParser.ParExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.parExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParExpression([NotNull] JavaParser.ParExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] JavaParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] JavaParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] JavaParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] JavaParser.MethodCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] JavaParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] JavaParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPattern([NotNull] JavaParser.PatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPattern([NotNull] JavaParser.PatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpression([NotNull] JavaParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpression([NotNull] JavaParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaParameters([NotNull] JavaParser.LambdaParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaParameters([NotNull] JavaParser.LambdaParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaBody([NotNull] JavaParser.LambdaBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaBody([NotNull] JavaParser.LambdaBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] JavaParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] JavaParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchExpression([NotNull] JavaParser.SwitchExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchExpression([NotNull] JavaParser.SwitchExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchLabeledRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchLabeledRule([NotNull] JavaParser.SwitchLabeledRuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchLabeledRule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchLabeledRule([NotNull] JavaParser.SwitchLabeledRuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.guardedPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuardedPattern([NotNull] JavaParser.GuardedPatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.guardedPattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuardedPattern([NotNull] JavaParser.GuardedPatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchRuleOutcome"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchRuleOutcome([NotNull] JavaParser.SwitchRuleOutcomeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchRuleOutcome"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchRuleOutcome([NotNull] JavaParser.SwitchRuleOutcomeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassType([NotNull] JavaParser.ClassTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassType([NotNull] JavaParser.ClassTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreator([NotNull] JavaParser.CreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.creator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreator([NotNull] JavaParser.CreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreatedName([NotNull] JavaParser.CreatedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.createdName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreatedName([NotNull] JavaParser.CreatedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.innerCreator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInnerCreator([NotNull] JavaParser.InnerCreatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.innerCreator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInnerCreator([NotNull] JavaParser.InnerCreatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayCreatorRest([NotNull] JavaParser.ArrayCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.arrayCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayCreatorRest([NotNull] JavaParser.ArrayCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassCreatorRest([NotNull] JavaParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classCreatorRest"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassCreatorRest([NotNull] JavaParser.ClassCreatorRestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.explicitGenericInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitGenericInvocation([NotNull] JavaParser.ExplicitGenericInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.explicitGenericInvocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitGenericInvocation([NotNull] JavaParser.ExplicitGenericInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgumentsOrDiamond([NotNull] JavaParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgumentsOrDiamond([NotNull] JavaParser.TypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonWildcardTypeArgumentsOrDiamond([NotNull] JavaParser.NonWildcardTypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonWildcardTypeArgumentsOrDiamond([NotNull] JavaParser.NonWildcardTypeArgumentsOrDiamondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.nonWildcardTypeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonWildcardTypeArguments([NotNull] JavaParser.NonWildcardTypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.nonWildcardTypeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonWildcardTypeArguments([NotNull] JavaParser.NonWildcardTypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeList([NotNull] JavaParser.TypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeList([NotNull] JavaParser.TypeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeType([NotNull] JavaParser.TypeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeType([NotNull] JavaParser.TypeTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] JavaParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] JavaParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArguments([NotNull] JavaParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArguments([NotNull] JavaParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.superSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuperSuffix([NotNull] JavaParser.SuperSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.superSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuperSuffix([NotNull] JavaParser.SuperSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.explicitGenericInvocationSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitGenericInvocationSuffix([NotNull] JavaParser.ExplicitGenericInvocationSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.explicitGenericInvocationSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitGenericInvocationSuffix([NotNull] JavaParser.ExplicitGenericInvocationSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] JavaParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] JavaParser.ArgumentsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
