//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/git/external/keycloak-openapi/Dahag.Keycloak.OpenApiGenerator\JavaParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JavaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IJavaParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] JavaParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] JavaParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.packageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackageDeclaration([NotNull] JavaParser.PackageDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.packageDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackageDeclaration([NotNull] JavaParser.PackageDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportDeclaration([NotNull] JavaParser.ImportDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.importDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportDeclaration([NotNull] JavaParser.ImportDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] JavaParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] JavaParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] JavaParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] JavaParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classOrInterfaceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceModifier([NotNull] JavaParser.ClassOrInterfaceModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classOrInterfaceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceModifier([NotNull] JavaParser.ClassOrInterfaceModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableModifier([NotNull] JavaParser.VariableModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableModifier([NotNull] JavaParser.VariableModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] JavaParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] JavaParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameters([NotNull] JavaParser.TypeParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameters([NotNull] JavaParser.TypeParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameter([NotNull] JavaParser.TypeParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameter([NotNull] JavaParser.TypeParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeBound([NotNull] JavaParser.TypeBoundContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeBound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeBound([NotNull] JavaParser.TypeBoundContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclaration([NotNull] JavaParser.EnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclaration([NotNull] JavaParser.EnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumConstants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumConstants([NotNull] JavaParser.EnumConstantsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumConstants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumConstants([NotNull] JavaParser.EnumConstantsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumConstant([NotNull] JavaParser.EnumConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumConstant([NotNull] JavaParser.EnumConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enumBodyDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBodyDeclarations([NotNull] JavaParser.EnumBodyDeclarationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enumBodyDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBodyDeclarations([NotNull] JavaParser.EnumBodyDeclarationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceDeclaration([NotNull] JavaParser.InterfaceDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceDeclaration([NotNull] JavaParser.InterfaceDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] JavaParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] JavaParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceBody([NotNull] JavaParser.InterfaceBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceBody([NotNull] JavaParser.InterfaceBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBodyDeclaration([NotNull] JavaParser.ClassBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBodyDeclaration([NotNull] JavaParser.ClassBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclaration([NotNull] JavaParser.MemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclaration([NotNull] JavaParser.MemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodDeclaration([NotNull] JavaParser.MethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodDeclaration([NotNull] JavaParser.MethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodBody([NotNull] JavaParser.MethodBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodBody([NotNull] JavaParser.MethodBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeTypeOrVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeTypeOrVoid([NotNull] JavaParser.TypeTypeOrVoidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeTypeOrVoid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeTypeOrVoid([NotNull] JavaParser.TypeTypeOrVoidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.genericMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericMethodDeclaration([NotNull] JavaParser.GenericMethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.genericMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericMethodDeclaration([NotNull] JavaParser.GenericMethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.genericConstructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericConstructorDeclaration([NotNull] JavaParser.GenericConstructorDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.genericConstructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericConstructorDeclaration([NotNull] JavaParser.GenericConstructorDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDeclaration([NotNull] JavaParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.constructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDeclaration([NotNull] JavaParser.ConstructorDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDeclaration([NotNull] JavaParser.FieldDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.fieldDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDeclaration([NotNull] JavaParser.FieldDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceBodyDeclaration([NotNull] JavaParser.InterfaceBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceBodyDeclaration([NotNull] JavaParser.InterfaceBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMemberDeclaration([NotNull] JavaParser.InterfaceMemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMemberDeclaration([NotNull] JavaParser.InterfaceMemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.constDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstDeclaration([NotNull] JavaParser.ConstDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.constDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstDeclaration([NotNull] JavaParser.ConstDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.constantDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantDeclarator([NotNull] JavaParser.ConstantDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.constantDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantDeclarator([NotNull] JavaParser.ConstantDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMethodDeclaration([NotNull] JavaParser.InterfaceMethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMethodDeclaration([NotNull] JavaParser.InterfaceMethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceMethodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceMethodModifier([NotNull] JavaParser.InterfaceMethodModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceMethodModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceMethodModifier([NotNull] JavaParser.InterfaceMethodModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.genericInterfaceMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericInterfaceMethodDeclaration([NotNull] JavaParser.GenericInterfaceMethodDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.genericInterfaceMethodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericInterfaceMethodDeclaration([NotNull] JavaParser.GenericInterfaceMethodDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.interfaceCommonBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaceCommonBodyDeclaration([NotNull] JavaParser.InterfaceCommonBodyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.interfaceCommonBodyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaceCommonBodyDeclaration([NotNull] JavaParser.InterfaceCommonBodyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarators([NotNull] JavaParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarators([NotNull] JavaParser.VariableDeclaratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] JavaParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] JavaParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaratorId([NotNull] JavaParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableDeclaratorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaratorId([NotNull] JavaParser.VariableDeclaratorIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableInitializer([NotNull] JavaParser.VariableInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.variableInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableInitializer([NotNull] JavaParser.VariableInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayInitializer([NotNull] JavaParser.ArrayInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayInitializer([NotNull] JavaParser.ArrayInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrInterfaceType([NotNull] JavaParser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classOrInterfaceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrInterfaceType([NotNull] JavaParser.ClassOrInterfaceTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgument([NotNull] JavaParser.TypeArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgument([NotNull] JavaParser.TypeArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.qualifiedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedNameList([NotNull] JavaParser.QualifiedNameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.qualifiedNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedNameList([NotNull] JavaParser.QualifiedNameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameters([NotNull] JavaParser.FormalParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameters([NotNull] JavaParser.FormalParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.receiverParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReceiverParameter([NotNull] JavaParser.ReceiverParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.receiverParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReceiverParameter([NotNull] JavaParser.ReceiverParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterList([NotNull] JavaParser.FormalParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterList([NotNull] JavaParser.FormalParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameter([NotNull] JavaParser.FormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameter([NotNull] JavaParser.FormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lastFormalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLastFormalParameter([NotNull] JavaParser.LastFormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lastFormalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLastFormalParameter([NotNull] JavaParser.LastFormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaLVTIList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaLVTIList([NotNull] JavaParser.LambdaLVTIListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaLVTIList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaLVTIList([NotNull] JavaParser.LambdaLVTIListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaLVTIParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaLVTIParameter([NotNull] JavaParser.LambdaLVTIParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaLVTIParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaLVTIParameter([NotNull] JavaParser.LambdaLVTIParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedName([NotNull] JavaParser.QualifiedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedName([NotNull] JavaParser.QualifiedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] JavaParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] JavaParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerLiteral([NotNull] JavaParser.IntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerLiteral([NotNull] JavaParser.IntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatLiteral([NotNull] JavaParser.FloatLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatLiteral([NotNull] JavaParser.FloatLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.altAnnotationQualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAltAnnotationQualifiedName([NotNull] JavaParser.AltAnnotationQualifiedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.altAnnotationQualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAltAnnotationQualifiedName([NotNull] JavaParser.AltAnnotationQualifiedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] JavaParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] JavaParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValuePairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementValuePairs([NotNull] JavaParser.ElementValuePairsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValuePairs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementValuePairs([NotNull] JavaParser.ElementValuePairsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementValuePair([NotNull] JavaParser.ElementValuePairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValuePair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementValuePair([NotNull] JavaParser.ElementValuePairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementValue([NotNull] JavaParser.ElementValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementValue([NotNull] JavaParser.ElementValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.elementValueArrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementValueArrayInitializer([NotNull] JavaParser.ElementValueArrayInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.elementValueArrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementValueArrayInitializer([NotNull] JavaParser.ElementValueArrayInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationTypeDeclaration([NotNull] JavaParser.AnnotationTypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationTypeDeclaration([NotNull] JavaParser.AnnotationTypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationTypeBody([NotNull] JavaParser.AnnotationTypeBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationTypeBody([NotNull] JavaParser.AnnotationTypeBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeElementDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationTypeElementDeclaration([NotNull] JavaParser.AnnotationTypeElementDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeElementDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationTypeElementDeclaration([NotNull] JavaParser.AnnotationTypeElementDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationTypeElementRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationTypeElementRest([NotNull] JavaParser.AnnotationTypeElementRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationTypeElementRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationTypeElementRest([NotNull] JavaParser.AnnotationTypeElementRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationMethodOrConstantRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationMethodOrConstantRest([NotNull] JavaParser.AnnotationMethodOrConstantRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationMethodOrConstantRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationMethodOrConstantRest([NotNull] JavaParser.AnnotationMethodOrConstantRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationMethodRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationMethodRest([NotNull] JavaParser.AnnotationMethodRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationMethodRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationMethodRest([NotNull] JavaParser.AnnotationMethodRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.annotationConstantRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationConstantRest([NotNull] JavaParser.AnnotationConstantRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.annotationConstantRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationConstantRest([NotNull] JavaParser.AnnotationConstantRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultValue([NotNull] JavaParser.DefaultValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.defaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultValue([NotNull] JavaParser.DefaultValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDeclaration([NotNull] JavaParser.ModuleDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.moduleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDeclaration([NotNull] JavaParser.ModuleDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleBody([NotNull] JavaParser.ModuleBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleBody([NotNull] JavaParser.ModuleBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.moduleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDirective([NotNull] JavaParser.ModuleDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.moduleDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDirective([NotNull] JavaParser.ModuleDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.requiresModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRequiresModifier([NotNull] JavaParser.RequiresModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.requiresModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRequiresModifier([NotNull] JavaParser.RequiresModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordDeclaration([NotNull] JavaParser.RecordDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordDeclaration([NotNull] JavaParser.RecordDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordHeader([NotNull] JavaParser.RecordHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordHeader([NotNull] JavaParser.RecordHeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordComponentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordComponentList([NotNull] JavaParser.RecordComponentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordComponentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordComponentList([NotNull] JavaParser.RecordComponentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordComponent([NotNull] JavaParser.RecordComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordComponent([NotNull] JavaParser.RecordComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.recordBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordBody([NotNull] JavaParser.RecordBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.recordBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordBody([NotNull] JavaParser.RecordBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] JavaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] JavaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatement([NotNull] JavaParser.BlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatement([NotNull] JavaParser.BlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalVariableDeclaration([NotNull] JavaParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalVariableDeclaration([NotNull] JavaParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] JavaParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] JavaParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.localTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocalTypeDeclaration([NotNull] JavaParser.LocalTypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.localTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocalTypeDeclaration([NotNull] JavaParser.LocalTypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] JavaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] JavaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.catchClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatchClause([NotNull] JavaParser.CatchClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.catchClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatchClause([NotNull] JavaParser.CatchClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.catchType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatchType([NotNull] JavaParser.CatchTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.catchType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatchType([NotNull] JavaParser.CatchTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.finallyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinallyBlock([NotNull] JavaParser.FinallyBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.finallyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinallyBlock([NotNull] JavaParser.FinallyBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.resourceSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResourceSpecification([NotNull] JavaParser.ResourceSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.resourceSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResourceSpecification([NotNull] JavaParser.ResourceSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.resources"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResources([NotNull] JavaParser.ResourcesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.resources"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResources([NotNull] JavaParser.ResourcesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResource([NotNull] JavaParser.ResourceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.resource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResource([NotNull] JavaParser.ResourceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchBlockStatementGroup([NotNull] JavaParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchBlockStatementGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchBlockStatementGroup([NotNull] JavaParser.SwitchBlockStatementGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchLabel([NotNull] JavaParser.SwitchLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchLabel([NotNull] JavaParser.SwitchLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForControl([NotNull] JavaParser.ForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForControl([NotNull] JavaParser.ForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInit([NotNull] JavaParser.ForInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInit([NotNull] JavaParser.ForInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.enhancedForControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnhancedForControl([NotNull] JavaParser.EnhancedForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.enhancedForControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnhancedForControl([NotNull] JavaParser.EnhancedForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParExpression([NotNull] JavaParser.ParExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.parExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParExpression([NotNull] JavaParser.ParExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] JavaParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] JavaParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCall([NotNull] JavaParser.MethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCall([NotNull] JavaParser.MethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] JavaParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] JavaParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPattern([NotNull] JavaParser.PatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.pattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPattern([NotNull] JavaParser.PatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpression([NotNull] JavaParser.LambdaExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpression([NotNull] JavaParser.LambdaExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaParameters([NotNull] JavaParser.LambdaParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaParameters([NotNull] JavaParser.LambdaParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaBody([NotNull] JavaParser.LambdaBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.lambdaBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaBody([NotNull] JavaParser.LambdaBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] JavaParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] JavaParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchExpression([NotNull] JavaParser.SwitchExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchExpression([NotNull] JavaParser.SwitchExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchLabeledRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchLabeledRule([NotNull] JavaParser.SwitchLabeledRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchLabeledRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchLabeledRule([NotNull] JavaParser.SwitchLabeledRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.guardedPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGuardedPattern([NotNull] JavaParser.GuardedPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.guardedPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGuardedPattern([NotNull] JavaParser.GuardedPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.switchRuleOutcome"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchRuleOutcome([NotNull] JavaParser.SwitchRuleOutcomeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.switchRuleOutcome"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchRuleOutcome([NotNull] JavaParser.SwitchRuleOutcomeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassType([NotNull] JavaParser.ClassTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassType([NotNull] JavaParser.ClassTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreator([NotNull] JavaParser.CreatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.creator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreator([NotNull] JavaParser.CreatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreatedName([NotNull] JavaParser.CreatedNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.createdName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreatedName([NotNull] JavaParser.CreatedNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.innerCreator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInnerCreator([NotNull] JavaParser.InnerCreatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.innerCreator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInnerCreator([NotNull] JavaParser.InnerCreatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.arrayCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayCreatorRest([NotNull] JavaParser.ArrayCreatorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.arrayCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayCreatorRest([NotNull] JavaParser.ArrayCreatorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassCreatorRest([NotNull] JavaParser.ClassCreatorRestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.classCreatorRest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassCreatorRest([NotNull] JavaParser.ClassCreatorRestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.explicitGenericInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitGenericInvocation([NotNull] JavaParser.ExplicitGenericInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.explicitGenericInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitGenericInvocation([NotNull] JavaParser.ExplicitGenericInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArgumentsOrDiamond([NotNull] JavaParser.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArgumentsOrDiamond([NotNull] JavaParser.TypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonWildcardTypeArgumentsOrDiamond([NotNull] JavaParser.NonWildcardTypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.nonWildcardTypeArgumentsOrDiamond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonWildcardTypeArgumentsOrDiamond([NotNull] JavaParser.NonWildcardTypeArgumentsOrDiamondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.nonWildcardTypeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonWildcardTypeArguments([NotNull] JavaParser.NonWildcardTypeArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.nonWildcardTypeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonWildcardTypeArguments([NotNull] JavaParser.NonWildcardTypeArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeList([NotNull] JavaParser.TypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeList([NotNull] JavaParser.TypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeType([NotNull] JavaParser.TypeTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeType([NotNull] JavaParser.TypeTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] JavaParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] JavaParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArguments([NotNull] JavaParser.TypeArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArguments([NotNull] JavaParser.TypeArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.superSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperSuffix([NotNull] JavaParser.SuperSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.superSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperSuffix([NotNull] JavaParser.SuperSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.explicitGenericInvocationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitGenericInvocationSuffix([NotNull] JavaParser.ExplicitGenericInvocationSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.explicitGenericInvocationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitGenericInvocationSuffix([NotNull] JavaParser.ExplicitGenericInvocationSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] JavaParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] JavaParser.ArgumentsContext context);
}
